//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

public partial class ChangePassword
{
    protected global::System.Web.UI.WebControls.Label Label1;
    protected global::System.Web.UI.WebControls.TextBox txtpassword;
    protected global::System.Web.UI.WebControls.RequiredFieldValidator rfpassword;
    protected global::System.Web.UI.WebControls.RegularExpressionValidator repassword;
    protected global::System.Web.UI.WebControls.Label Label2;
    protected global::System.Web.UI.WebControls.TextBox txtnewpassword;
    protected global::System.Web.UI.WebControls.RequiredFieldValidator rfnewpassword;
    protected global::System.Web.UI.WebControls.RegularExpressionValidator renewpassword;
    protected global::System.Web.UI.WebControls.CompareValidator nePassword;
    protected global::System.Web.UI.WebControls.Label Label3;
    protected global::System.Web.UI.WebControls.TextBox txtconfirmpassword;
    protected global::System.Web.UI.WebControls.RequiredFieldValidator rfconfirmpassword;
    protected global::System.Web.UI.WebControls.RegularExpressionValidator reconfirmpassword;
    protected global::System.Web.UI.WebControls.CompareValidator cvPassword;
    protected global::System.Web.UI.WebControls.Button btnupdate;
    protected global::System.Web.UI.WebControls.Button btnreset;
    protected global::System.Web.UI.WebControls.Button btnBack;
    protected global::System.Web.UI.WebControls.ValidationSummary vssummary;
}
