//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

public partial class MasterMaint_LabelPlan_Dtl : Control.Base
{
    protected global::App_Module_Title UCTitle;
    protected global::App_Module_ErrorReport UCError;
    protected global::System.Web.UI.WebControls.Panel Cdisplay;
    protected global::System.Web.UI.WebControls.Label Label13;
    protected global::System.Web.UI.WebControls.Label Label14;
    protected global::System.Web.UI.WebControls.Label lblCompCode;
    protected global::System.Web.UI.WebControls.Label Label11;
    protected global::System.Web.UI.WebControls.Label Label12;
    protected global::System.Web.UI.WebControls.Label lblPlanYrMth;
    protected global::System.Web.UI.WebControls.Label Label3;
    protected global::System.Web.UI.WebControls.Label Label4;
    protected global::System.Web.UI.WebControls.Label lblProdLine;
    protected global::System.Web.UI.WebControls.Label Label19;
    protected global::System.Web.UI.WebControls.Label Labe20;
    protected global::System.Web.UI.WebControls.Label lblPC1Mother;
    protected global::System.Web.UI.WebControls.Label Label1;
    protected global::System.Web.UI.WebControls.Label Label2;
    protected global::System.Web.UI.WebControls.Label lblPC2Mother;
    protected global::System.Web.UI.WebControls.Label Label15;
    protected global::System.Web.UI.WebControls.Label Label16;
    protected global::System.Web.UI.WebControls.Label lblUnitWeightMother;
    protected global::System.Web.UI.WebControls.Label Label17;
    protected global::System.Web.UI.WebControls.Label Label18;
    protected global::System.Web.UI.WebControls.Label lblPC1Customer;
    protected global::System.Web.UI.WebControls.Label Label6;
    protected global::System.Web.UI.WebControls.Label Label9;
    protected global::System.Web.UI.WebControls.Label lblPC2Customer;
    protected global::System.Web.UI.WebControls.Label Label5;
    protected global::System.Web.UI.WebControls.Label Label10;
    protected global::System.Web.UI.WebControls.Label lblUnitWeightCustomer;
    protected global::System.Web.UI.WebControls.Label Label21;
    protected global::System.Web.UI.WebControls.Label Label22;
    protected global::System.Web.UI.WebControls.Label lblLotNo;
    protected global::System.Web.UI.WebControls.Label Label20;
    protected global::System.Web.UI.WebControls.Label Label41;
    protected global::System.Web.UI.WebControls.Label lblLotSlitNo;
    protected global::System.Web.UI.WebControls.Label Label7;
    protected global::System.Web.UI.WebControls.Label Label8;
    protected global::System.Web.UI.WebControls.Label lblStatus;
    protected global::App_Module_Controller UCAction;
}
