//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

public partial class MasterMaint_MM_COMPANY_Dtl : Control.Base
{
    protected global::App_Module_Title UCTitle;
    protected global::App_Module_ErrorReport UCError;
    protected global::System.Web.UI.WebControls.Panel Cdisplay;
    protected global::System.Web.UI.WebControls.Label Label1;
    protected global::System.Web.UI.WebControls.Label Label2;
    protected global::System.Web.UI.WebControls.Label lblCompCode;
    protected global::System.Web.UI.WebControls.Label Label3;
    protected global::System.Web.UI.WebControls.Label Label4;
    protected global::System.Web.UI.WebControls.Label lblCompName;
    protected global::System.Web.UI.WebControls.Label Label5;
    protected global::System.Web.UI.WebControls.Label Label6;
    protected global::System.Web.UI.WebControls.Label lblAddress;
    protected global::System.Web.UI.WebControls.Label Label7;
    protected global::System.Web.UI.WebControls.Label Label8;
    protected global::System.Web.UI.WebControls.Label lblTelephone;
    protected global::System.Web.UI.WebControls.Label Label12;
    protected global::System.Web.UI.WebControls.Label Label13;
    protected global::System.Web.UI.WebControls.Label lblEmail;
    protected global::System.Web.UI.WebControls.Label Label29;
    protected global::System.Web.UI.WebControls.Label Label30;
    protected global::System.Web.UI.WebControls.Label lblslit;
    protected global::System.Web.UI.WebControls.Panel Cmodify;
    protected global::System.Web.UI.WebControls.Label Label15;
    protected global::System.Web.UI.WebControls.Label Label16;
    protected global::System.Web.UI.WebControls.Label Label17;
    protected global::System.Web.UI.WebControls.Label lbCompCode;
    protected global::System.Web.UI.WebControls.TextBox txtCompCode;
    protected global::System.Web.UI.WebControls.RequiredFieldValidator rfCompCode;
    protected global::System.Web.UI.WebControls.Label Label18;
    protected global::System.Web.UI.WebControls.Label Label19;
    protected global::System.Web.UI.WebControls.Label Label20;
    protected global::System.Web.UI.WebControls.TextBox txtCompName;
    protected global::System.Web.UI.WebControls.RequiredFieldValidator rfCompName;
    protected global::System.Web.UI.WebControls.Label Label21;
    protected global::System.Web.UI.WebControls.Label Label22;
    protected global::System.Web.UI.WebControls.Label Label23;
    protected global::System.Web.UI.WebControls.TextBox txtAddress;
    protected global::System.Web.UI.WebControls.RequiredFieldValidator rfAddress;
    protected global::System.Web.UI.WebControls.Label Label9;
    protected global::System.Web.UI.WebControls.Label Label10;
    protected global::System.Web.UI.WebControls.Label Label11;
    protected global::System.Web.UI.WebControls.TextBox txtTelephone;
    protected global::System.Web.UI.WebControls.RequiredFieldValidator rfTelephone;
    protected global::System.Web.UI.WebControls.Label Label24;
    protected global::System.Web.UI.WebControls.Label Label25;
    protected global::System.Web.UI.WebControls.Label Label26;
    protected global::System.Web.UI.WebControls.TextBox txtEmail;
    protected global::System.Web.UI.WebControls.RequiredFieldValidator rfEmail;
    protected global::System.Web.UI.WebControls.RegularExpressionValidator rfEmail2;
    protected global::System.Web.UI.WebControls.Label Label14;
    protected global::System.Web.UI.WebControls.Label Label27;
    protected global::System.Web.UI.WebControls.Label Label28;
    protected global::System.Web.UI.WebControls.TextBox txtSlit;
    protected global::System.Web.UI.WebControls.RequiredFieldValidator rfSlit;
    protected global::App_Module_Controller UCAction;
}
