//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

public partial class MasterMaint_MM_PRODLINE_Dtl : Control.Base
{
    protected global::App_Module_Title UCTitle;
    protected global::App_Module_ErrorReport UCError;
    protected global::System.Web.UI.WebControls.Panel Cdisplay;
    protected global::System.Web.UI.WebControls.Label Label11;
    protected global::System.Web.UI.WebControls.Label Label12;
    protected global::System.Web.UI.WebControls.Label lblProdLine;
    protected global::System.Web.UI.WebControls.Label Label3;
    protected global::System.Web.UI.WebControls.Label Label4;
    protected global::System.Web.UI.WebControls.Label lblDesc;
    protected global::System.Web.UI.WebControls.Panel Cmodify;
    protected global::System.Web.UI.WebControls.Label Label23;
    protected global::System.Web.UI.WebControls.Label Label24;
    protected global::System.Web.UI.WebControls.Label labelProdLine;
    protected global::System.Web.UI.WebControls.Label lbProdLine;
    protected global::System.Web.UI.WebControls.TextBox txtProdLine;
    protected global::System.Web.UI.WebControls.RequiredFieldValidator rfProdLine;
    protected global::System.Web.UI.WebControls.Label Label21;
    protected global::System.Web.UI.WebControls.Label Label27;
    protected global::System.Web.UI.WebControls.Label lbDesc;
    protected global::System.Web.UI.WebControls.TextBox txtDesc;
    protected global::App_Module_Controller UCAction;
}
