//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

public partial class MasterMaint_MM_PC1_Dtl : Control.Base
{
    protected global::App_Module_Title UCTitle;
    protected global::App_Module_ErrorReport UCError;
    protected global::System.Web.UI.WebControls.Panel Cdisplay;
    protected global::System.Web.UI.WebControls.Label Label1;
    protected global::System.Web.UI.WebControls.Label Label2;
    protected global::System.Web.UI.WebControls.Label lblPC1;
    protected global::System.Web.UI.WebControls.Label Label3;
    protected global::System.Web.UI.WebControls.Label Label4;
    protected global::System.Web.UI.WebControls.Label lblNameDelivery;
    protected global::System.Web.UI.WebControls.Panel Cmodify;
    protected global::System.Web.UI.WebControls.Label Label15;
    protected global::System.Web.UI.WebControls.Label Label16;
    protected global::System.Web.UI.WebControls.Label Label17;
    protected global::System.Web.UI.WebControls.Label lbPC1;
    protected global::System.Web.UI.WebControls.TextBox txtPC1;
    protected global::System.Web.UI.WebControls.RequiredFieldValidator rfPC1;
    protected global::System.Web.UI.WebControls.Label Label18;
    protected global::System.Web.UI.WebControls.Label Label19;
    protected global::System.Web.UI.WebControls.Label Label20;
    protected global::System.Web.UI.WebControls.TextBox txtNameDelivery;
    protected global::System.Web.UI.WebControls.RequiredFieldValidator rfNameDelivery;
    protected global::App_Module_Controller UCAction;
}
