//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

public partial class MasterMaint_MM_USER_Dtl : Control.Base
{
    protected global::App_Module_Title UCTitle;
    protected global::App_Module_ErrorReport UCError;
    protected global::System.Web.UI.WebControls.Panel Cdisplay;
    protected global::System.Web.UI.WebControls.Label Label11;
    protected global::System.Web.UI.WebControls.Label Label12;
    protected global::System.Web.UI.WebControls.Label lblCompName;
    protected global::System.Web.UI.WebControls.Label Label1;
    protected global::System.Web.UI.WebControls.Label Label2;
    protected global::System.Web.UI.WebControls.Label lblName;
    protected global::System.Web.UI.WebControls.Label Label3;
    protected global::System.Web.UI.WebControls.Label Label4;
    protected global::System.Web.UI.WebControls.Label lblUserID;
    protected global::System.Web.UI.WebControls.Label Label5;
    protected global::System.Web.UI.WebControls.Label Label6;
    protected global::System.Web.UI.WebControls.Label lblDepartment;
    protected global::System.Web.UI.WebControls.Label Label7;
    protected global::System.Web.UI.WebControls.Label Label8;
    protected global::System.Web.UI.WebControls.Label lblEmail;
    protected global::System.Web.UI.WebControls.Label Label9;
    protected global::System.Web.UI.WebControls.Label Label10;
    protected global::System.Web.UI.WebControls.Label lblLevel;
    protected global::System.Web.UI.WebControls.Label Label35;
    protected global::System.Web.UI.WebControls.Label Label36;
    protected global::System.Web.UI.WebControls.Label lblaccstats;
    protected global::System.Web.UI.WebControls.Panel Cmodify;
    protected global::System.Web.UI.WebControls.Label Label13;
    protected global::System.Web.UI.WebControls.Label Label14;
    protected global::System.Web.UI.WebControls.Label Label33;
    protected global::System.Web.UI.WebControls.Label lbCompName;
    protected global::System.Web.UI.WebControls.DropDownList ddlCompName;
    protected global::System.Web.UI.WebControls.RequiredFieldValidator rfCompName;
    protected global::System.Web.UI.WebControls.Label Label15;
    protected global::System.Web.UI.WebControls.Label Label16;
    protected global::System.Web.UI.WebControls.Label Label17;
    protected global::System.Web.UI.WebControls.TextBox txtName;
    protected global::System.Web.UI.WebControls.RequiredFieldValidator rfName;
    protected global::System.Web.UI.WebControls.Label Label18;
    protected global::System.Web.UI.WebControls.Label Label19;
    protected global::System.Web.UI.WebControls.Label Label20;
    protected global::System.Web.UI.WebControls.Label lbUserID;
    protected global::System.Web.UI.WebControls.TextBox txtUserID;
    protected global::System.Web.UI.WebControls.RequiredFieldValidator rfUserID;
    protected global::System.Web.UI.WebControls.Label Label21;
    protected global::System.Web.UI.WebControls.Label Label22;
    protected global::System.Web.UI.WebControls.Label Label23;
    protected global::System.Web.UI.WebControls.TextBox txtDepartment;
    protected global::System.Web.UI.WebControls.RequiredFieldValidator rfDepartment;
    protected global::System.Web.UI.WebControls.Label Label24;
    protected global::System.Web.UI.WebControls.Label Label25;
    protected global::System.Web.UI.WebControls.Label Label26;
    protected global::System.Web.UI.WebControls.TextBox txtEmail;
    protected global::System.Web.UI.WebControls.RequiredFieldValidator rfEmail;
    protected global::System.Web.UI.WebControls.RegularExpressionValidator rfEmail2;
    protected global::System.Web.UI.WebControls.RadioButton RBLevel1;
    protected global::System.Web.UI.WebControls.TextBox TextBox1;
    protected global::System.Web.UI.WebControls.RequiredFieldValidator rfRB;
    protected global::System.Web.UI.WebControls.Label Label27;
    protected global::System.Web.UI.WebControls.Label Label28;
    protected global::System.Web.UI.WebControls.Label Label29;
    protected global::System.Web.UI.WebControls.RadioButton RBLevel2;
    protected global::System.Web.UI.WebControls.RadioButton RBLevel3;
    protected global::System.Web.UI.WebControls.Label Label34;
    protected global::System.Web.UI.WebControls.Label Label37;
    protected global::System.Web.UI.WebControls.Label Label38;
    protected global::System.Web.UI.WebControls.Label lblAccStats2;
    protected global::System.Web.UI.WebControls.DropDownList ddlAccStats;
    protected global::System.Web.UI.WebControls.RequiredFieldValidator RFddlaccstats;
    protected global::System.Web.UI.HtmlControls.HtmlTableRow tblpassword;
    protected global::System.Web.UI.WebControls.Label Label30;
    protected global::System.Web.UI.WebControls.Label Label31;
    protected global::System.Web.UI.WebControls.Label Label32;
    protected global::System.Web.UI.WebControls.TextBox txtPassword;
    protected global::System.Web.UI.WebControls.RegularExpressionValidator rePassword;
    protected global::System.Web.UI.WebControls.RequiredFieldValidator rfPassword;
    protected global::System.Web.UI.WebControls.LinkButton resetlnk;
    protected global::App_Module_Controller UCAction;
}
