//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

public partial class MasterMaint_PRINT_ALIGN_INIT : Control.Base
{
    protected global::App_Module_Title UCTitle;
    protected global::Search UCSearch;
    protected global::UserControl_GridHeader UCHeader;
    protected global::System.Web.UI.WebControls.GridView grdResult;
    protected global::UserControl_GridFooter UCFooter;
    protected global::System.Web.UI.WebControls.Label Label1;
    protected global::System.Web.UI.WebControls.Label Label2;
    protected global::System.Web.UI.WebControls.LinkButton herebutton;
    protected global::System.Web.UI.WebControls.LinkButton hereButton1;
    protected global::System.Web.UI.WebControls.Label Label3;
    protected global::System.Web.UI.WebControls.Label Label4;
}
