'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.5420
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option or rebuild the Visual Studio project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "9.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class DetailPage
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Resources.DetailPage", Global.System.Reflection.[Assembly].Load("App_GlobalResources"))
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ~/acc/MstMain/HoldScheduleOrder.aspx?action=1.
        '''</summary>
        Friend Shared ReadOnly Property HoldScheduleOrder() As String
            Get
                Return ResourceManager.GetString("HoldScheduleOrder", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ~/acc/MstMain/ManualScheduleAdd.aspx.
        '''</summary>
        Friend Shared ReadOnly Property ManualSchedule() As String
            Get
                Return ResourceManager.GetString("ManualSchedule", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ~/acc/MstMain/MM_COMM_DETAIL.aspx.
        '''</summary>
        Friend Shared ReadOnly Property MM_COMM_FIELD() As String
            Get
                Return ResourceManager.GetString("MM_COMM_FIELD", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ~/WIPRFID_web/Web/acc/MstMaint/MM_Email_Group_Dtl.aspx.
        '''</summary>
        Friend Shared ReadOnly Property MM_Email_Group() As String
            Get
                Return ResourceManager.GetString("MM_Email_Group", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ~/WIPRFID_web/Web/acc/MstMaint/MM_Email_List_Dtl.aspx.
        '''</summary>
        Friend Shared ReadOnly Property MM_Email_List() As String
            Get
                Return ResourceManager.GetString("MM_Email_List", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ~/WIPRFID_web/Web/acc/MstMaint/MM_Equipment_Dtl.aspx.
        '''</summary>
        Friend Shared ReadOnly Property MM_Equipment() As String
            Get
                Return ResourceManager.GetString("MM_Equipment", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ~/WIPRFID_web/Web/acc/MstMaint/MM_Equipment_Reg_Dtl.aspx.
        '''</summary>
        Friend Shared ReadOnly Property MM_Equipment_Reg() As String
            Get
                Return ResourceManager.GetString("MM_Equipment_Reg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ~/acc/MstMain/MM_Mac_CondDtl.aspx.
        '''</summary>
        Friend Shared ReadOnly Property MM_Mac_Cond() As String
            Get
                Return ResourceManager.GetString("MM_Mac_Cond", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ~/WIPRFID_web/Web/acc/MstMaint/MM_RFID_LOC_AREA_Dtl.aspx.
        '''</summary>
        Friend Shared ReadOnly Property MM_RFID_LOC_AREA() As String
            Get
                Return ResourceManager.GetString("MM_RFID_LOC_AREA", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ~/WIPRFID_web/Web/acc/MstMaint/MM_RFID_LOC_READER_REG_Dtl.aspx.
        '''</summary>
        Friend Shared ReadOnly Property MM_RFID_LOC_READER_REG() As String
            Get
                Return ResourceManager.GetString("MM_RFID_LOC_READER_REG", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ~/WIPRFID_web/Web/acc/MstMaint/MM_RFID_Type_Dtl.aspx.
        '''</summary>
        Friend Shared ReadOnly Property MM_RFID_Type() As String
            Get
                Return ResourceManager.GetString("MM_RFID_Type", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ~/acc/MstMain/MM_ST_CONTROLDtl.aspx.
        '''</summary>
        Friend Shared ReadOnly Property MM_ST_CONTROL() As String
            Get
                Return ResourceManager.GetString("MM_ST_CONTROL", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ~/MasterMaint/MM_USER_Dtl.aspx.
        '''</summary>
        Friend Shared ReadOnly Property MM_USER() As String
            Get
                Return ResourceManager.GetString("MM_USER", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ~/acc/MstMain/RptSch.aspx.
        '''</summary>
        Friend Shared ReadOnly Property RptSch() As String
            Get
                Return ResourceManager.GetString("RptSch", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ~/acc/MstMain/ScheduleController.aspx?action=1.
        '''</summary>
        Friend Shared ReadOnly Property ScheduleController() As String
            Get
                Return ResourceManager.GetString("ScheduleController", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to ~/MasterMaint/MM_PC1_Dtl.aspx.
        '''</summary>
        Friend Shared ReadOnly Property MM_PC1() As String
            Get
                Return ResourceManager.GetString("MM_PC1", resourceCulture)
            End Get
        End Property

        Friend Shared ReadOnly Property MM_PC2_MOTHER() As String
            Get
                Return ResourceManager.GetString("MM_PC2_MOTHER", resourceCulture)
            End Get
        End Property

        Friend Shared ReadOnly Property PRINT_ALIGN_INIT() As String
            Get
                Return ResourceManager.GetString("PRINT_ALIGN_INIT", resourceCulture)
            End Get
        End Property

        Friend Shared ReadOnly Property MM_PC2() As String
            Get
                Return ResourceManager.GetString("MM_PC2", resourceCulture)
            End Get
        End Property

        Friend Shared ReadOnly Property MM_COMPANY() As String
            Get
                Return ResourceManager.GetString("MM_COMPANY", resourceCulture)
            End Get
        End Property

        Friend Shared ReadOnly Property MM_PRODLINE() As String
            Get
                Return ResourceManager.GetString("MM_PRODLINE", resourceCulture)
            End Get
        End Property

        Friend Shared ReadOnly Property VIEW_LOT_SLITTING_SERIES() As String
            Get
                Return ResourceManager.GetString("VIEW_LOT_SLITTING_SERIES", resourceCulture)
            End Get
        End Property

        Friend Shared ReadOnly Property PV_SUBSLIT_REQUEST_LIST() As String
            Get
                Return ResourceManager.GetString("PV_SUBSLIT_REQUEST_LIST", resourceCulture)
            End Get
        End Property

        Friend Shared ReadOnly Property PC2_LOTNO() As String
            Get
                Return ResourceManager.GetString("PC2_LOTNO", resourceCulture)
            End Get
        End Property

    End Class
End Namespace
