//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DetailPage {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DetailPage() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.DetailPage", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/acc/MstMain/HoldScheduleOrder.aspx?action=1.
        /// </summary>
        internal static string HoldScheduleOrder {
            get {
                return ResourceManager.GetString("HoldScheduleOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/acc/MstMain/ManualScheduleAdd.aspx.
        /// </summary>
        internal static string ManualSchedule {
            get {
                return ResourceManager.GetString("ManualSchedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/acc/MstMain/MM_COMM_DETAIL.aspx.
        /// </summary>
        internal static string MM_COMM_FIELD {
            get {
                return ResourceManager.GetString("MM_COMM_FIELD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/MasterMaint/MM_COMPANY_Dtl.aspx.
        /// </summary>
        internal static string MM_COMPANY {
            get {
                return ResourceManager.GetString("MM_COMPANY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/WIPRFID_web/Web/acc/MstMaint/MM_Email_Group_Dtl.aspx.
        /// </summary>
        internal static string MM_Email_Group {
            get {
                return ResourceManager.GetString("MM_Email_Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/WIPRFID_web/Web/acc/MstMaint/MM_Email_List_Dtl.aspx.
        /// </summary>
        internal static string MM_Email_List {
            get {
                return ResourceManager.GetString("MM_Email_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/WIPRFID_web/Web/acc/MstMaint/MM_Equipment_Dtl.aspx.
        /// </summary>
        internal static string MM_Equipment {
            get {
                return ResourceManager.GetString("MM_Equipment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/WIPRFID_web/Web/acc/MstMaint/MM_Equipment_Reg_Dtl.aspx.
        /// </summary>
        internal static string MM_Equipment_Reg {
            get {
                return ResourceManager.GetString("MM_Equipment_Reg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/acc/MstMain/MM_Mac_CondDtl.aspx.
        /// </summary>
        internal static string MM_Mac_Cond {
            get {
                return ResourceManager.GetString("MM_Mac_Cond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/MasterMaint/MM_PC1_Dtl.aspx.
        /// </summary>
        internal static string MM_PC1 {
            get {
                return ResourceManager.GetString("MM_PC1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/MasterMaint/MM_PC2_Dtl.aspx.
        /// </summary>
        internal static string MM_PC2 {
            get {
                return ResourceManager.GetString("MM_PC2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/MasterMaint/MM_PC2_MOTHER_Dtl.aspx.
        /// </summary>
        internal static string MM_PC2_MOTHER {
            get {
                return ResourceManager.GetString("MM_PC2_MOTHER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/MasterMaint/MM_PRODLINE_Dtl.aspx.
        /// </summary>
        internal static string MM_PRODLINE {
            get {
                return ResourceManager.GetString("MM_PRODLINE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/WIPRFID_web/Web/acc/MstMaint/MM_RFID_LOC_AREA_Dtl.aspx.
        /// </summary>
        internal static string MM_RFID_LOC_AREA {
            get {
                return ResourceManager.GetString("MM_RFID_LOC_AREA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/WIPRFID_web/Web/acc/MstMaint/MM_RFID_LOC_READER_REG_Dtl.aspx.
        /// </summary>
        internal static string MM_RFID_LOC_READER_REG {
            get {
                return ResourceManager.GetString("MM_RFID_LOC_READER_REG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/WIPRFID_web/Web/acc/MstMaint/MM_RFID_Type_Dtl.aspx.
        /// </summary>
        internal static string MM_RFID_Type {
            get {
                return ResourceManager.GetString("MM_RFID_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/acc/MstMain/MM_ST_CONTROLDtl.aspx.
        /// </summary>
        internal static string MM_ST_CONTROL {
            get {
                return ResourceManager.GetString("MM_ST_CONTROL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/MasterMaint/MM_USER_Dtl.aspx.
        /// </summary>
        internal static string MM_USER {
            get {
                return ResourceManager.GetString("MM_USER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Transactions/SLIT_SERIES_Dtl.aspx.
        /// </summary>
        internal static string PC2_LOTNO {
            get {
                return ResourceManager.GetString("PC2_LOTNO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/MasterMaint/PRINT_ALIGN_INIT_Dtl.aspx.
        /// </summary>
        internal static string PRINT_ALIGN_INIT {
            get {
                return ResourceManager.GetString("PRINT_ALIGN_INIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Transactions/SSR_SEARCH_Dtl.aspx.
        /// </summary>
        internal static string PV_SUBSLIT_REQUEST_LIST {
            get {
                return ResourceManager.GetString("PV_SUBSLIT_REQUEST_LIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/acc/MstMain/RptSch.aspx.
        /// </summary>
        internal static string RptSch {
            get {
                return ResourceManager.GetString("RptSch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/acc/MstMain/ScheduleController.aspx?action=1.
        /// </summary>
        internal static string ScheduleController {
            get {
                return ResourceManager.GetString("ScheduleController", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/MasterMaint/LabelPlan_Dtl.aspx.
        /// </summary>
        internal static string VIEW_LOT_SLITTING_SERIES {
            get {
                return ResourceManager.GetString("VIEW_LOT_SLITTING_SERIES", resourceCulture);
            }
        }
    }
}
