//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Log {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Log() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Log", typeof(Log).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MM_COMM_FIELD_A.
        /// </summary>
        internal static string MM_COMM_FIELD {
            get {
                return ResourceManager.GetString("MM_COMM_FIELD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MM_COMPANY_A.
        /// </summary>
        internal static string MM_COMPANY {
            get {
                return ResourceManager.GetString("MM_COMPANY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to V_MM_EMAIL_GROUP_A.
        /// </summary>
        internal static string MM_Email_Group {
            get {
                return ResourceManager.GetString("MM_Email_Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to V_MM_EMAIL_LIST_A.
        /// </summary>
        internal static string MM_Email_List {
            get {
                return ResourceManager.GetString("MM_Email_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PVIEW_MM_Equipment_A.
        /// </summary>
        internal static string MM_Equipment {
            get {
                return ResourceManager.GetString("MM_Equipment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PVIEW_MM_EQUIPMENT_REG_A.
        /// </summary>
        internal static string MM_Equipment_Reg {
            get {
                return ResourceManager.GetString("MM_Equipment_Reg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PVIEW_MM_SETUP_LOG.
        /// </summary>
        internal static string MM_Mac_Cond {
            get {
                return ResourceManager.GetString("MM_Mac_Cond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MM_PC1_A.
        /// </summary>
        internal static string MM_PC1 {
            get {
                return ResourceManager.GetString("MM_PC1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MM_PC2_A.
        /// </summary>
        internal static string MM_PC2 {
            get {
                return ResourceManager.GetString("MM_PC2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MM_PC2_MOTHER_A.
        /// </summary>
        internal static string MM_PC2_MOTHER {
            get {
                return ResourceManager.GetString("MM_PC2_MOTHER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MM_PRODLINE_A.
        /// </summary>
        internal static string MM_PRODLINE {
            get {
                return ResourceManager.GetString("MM_PRODLINE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PVIEW_MM_RFID_LOC_AREA_A.
        /// </summary>
        internal static string MM_RFID_LOC_AREA {
            get {
                return ResourceManager.GetString("MM_RFID_LOC_AREA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PVIEW_MM_RFID_LOC_READER_REG_A.
        /// </summary>
        internal static string MM_RFID_LOC_READER_REG {
            get {
                return ResourceManager.GetString("MM_RFID_LOC_READER_REG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PVIEW_MM_RFID_TYPE_A.
        /// </summary>
        internal static string MM_RFID_Type {
            get {
                return ResourceManager.GetString("MM_RFID_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MM_USER_A.
        /// </summary>
        internal static string MM_USER {
            get {
                return ResourceManager.GetString("MM_USER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PRINT_ALIGN_INIT_A.
        /// </summary>
        internal static string PRINT_ALIGN_INIT {
            get {
                return ResourceManager.GetString("PRINT_ALIGN_INIT", resourceCulture);
            }
        }
    }
}