//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Message {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Message() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Message", typeof(Message).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access Denied!.
        /// </summary>
        internal static string AccessDenied {
            get {
                return ResourceManager.GetString("AccessDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Already Exists!.
        /// </summary>
        internal static string AlreadyExists {
            get {
                return ResourceManager.GetString("AlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Select At Least One Selection..
        /// </summary>
        internal static string AtLeastOneSelection {
            get {
                return ResourceManager.GetString("AtLeastOneSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Must be Between {1} and {2}.
        /// </summary>
        internal static string Between {
            get {
                return ResourceManager.GetString("Between", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The condition is empty..
        /// </summary>
        internal static string ConditionEmpty {
            get {
                return ResourceManager.GetString("ConditionEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you going to delete the search condition?.
        /// </summary>
        internal static string ConfirmDeleteConditionMsg {
            get {
                return ResourceManager.GetString("ConfirmDeleteConditionMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Must Be {1} or {2}.
        /// </summary>
        internal static string ContainValue {
            get {
                return ResourceManager.GetString("ContainValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue without search condition?.
        /// </summary>
        internal static string ContinueWithoutCondition {
            get {
                return ResourceManager.GetString("ContinueWithoutCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data No Ready - {0}.
        /// </summary>
        internal static string DataNoReady {
            get {
                return ResourceManager.GetString("DataNoReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data In {0} Table Not Defined!.
        /// </summary>
        internal static string DataNotDefine {
            get {
                return ResourceManager.GetString("DataNotDefine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Must be {1}.
        /// </summary>
        internal static string DataTypeError {
            get {
                return ResourceManager.GetString("DataTypeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Date Format. e.g. 01-Feb-2001.
        /// </summary>
        internal static string DateDDMMMYYYYFormat {
            get {
                return ResourceManager.GetString("DateDDMMMYYYYFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}, Invalid Date Format. e.g. 28-02-2013!.
        /// </summary>
        internal static string DateDDMMYYYYFormat {
            get {
                return ResourceManager.GetString("DateDDMMYYYYFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Account Month Format. (YYYYMM).
        /// </summary>
        internal static string DateYYYYMMFormat {
            get {
                return ResourceManager.GetString("DateYYYYMMFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure want to delete this record?.
        /// </summary>
        internal static string DeleteConfirmation {
            get {
                return ResourceManager.GetString("DeleteConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Choose Yes to confirm delete.
        /// </summary>
        internal static string Deletemessage {
            get {
                return ResourceManager.GetString("Deletemessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate {0}!.
        /// </summary>
        internal static string Duplicate {
            get {
                return ResourceManager.GetString("Duplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning :.
        /// </summary>
        internal static string ErrorHeader {
            get {
                return ResourceManager.GetString("ErrorHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Failed!.
        /// </summary>
        internal static string Failed {
            get {
                return ResourceManager.GetString("Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Cannot be Empty!.
        /// </summary>
        internal static string FieldEmpty {
            get {
                return ResourceManager.GetString("FieldEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must in Alphanumeric Format!.
        /// </summary>
        internal static string FieldFormatAlphanumericError {
            get {
                return ResourceManager.GetString("FieldFormatAlphanumericError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must in Numeric Format!.
        /// </summary>
        internal static string FieldFormatNumericError {
            get {
                return ResourceManager.GetString("FieldFormatNumericError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished Goods Transfer Note {0}, {1} Not Allowed! Note Already Closed..
        /// </summary>
        internal static string FinGoodsTransferActionStoped {
            get {
                return ResourceManager.GetString("FinGoodsTransferActionStoped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Items Found, At Least 1 Item Must Be Filled..
        /// </summary>
        internal static string FinGoodsTransferItemEmpty {
            get {
                return ResourceManager.GetString("FinGoodsTransferItemEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Item No {0} Quantity, Transfer Quantity Must Greater Than 0..
        /// </summary>
        internal static string FinGoodsTransferItemQtyZero {
            get {
                return ResourceManager.GetString("FinGoodsTransferItemQtyZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished Goods Transfer, {0} Not Allowed! Month-End Closing Already Run..
        /// </summary>
        internal static string FinGoodsTransferMonthEndClosed {
            get {
                return ResourceManager.GetString("FinGoodsTransferMonthEndClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Pallet No {0} Quantity, Pallet Quantity Must Greater Than 0..
        /// </summary>
        internal static string FinGoodsTransferPalletQtyZero {
            get {
                return ResourceManager.GetString("FinGoodsTransferPalletQtyZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid character for advance search.
        /// </summary>
        internal static string InvalidAdvanceSearch {
            get {
                return ResourceManager.GetString("InvalidAdvanceSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid character for basic search.
        /// </summary>
        internal static string InvalidBasicSearch {
            get {
                return ResourceManager.GetString("InvalidBasicSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Receiving Lot and Item, Existing Lot {0} for Specified Item {1} Not Foun....
        /// </summary>
        internal static string InvalidItemNo_ReceivedLot {
            get {
                return ResourceManager.GetString("InvalidItemNo_ReceivedLot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid {0}.
        /// </summary>
        internal static string InvalidPasswordUserName {
            get {
                return ResourceManager.GetString("InvalidPasswordUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Process!.
        /// </summary>
        internal static string InvalidProcess {
            get {
                return ResourceManager.GetString("InvalidProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Selection.
        /// </summary>
        internal static string InvalidSelect {
            get {
                return ResourceManager.GetString("InvalidSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid {0}, Record Not Found In Master Table..
        /// </summary>
        internal static string MasterMaintenanceRecordNotFound {
            get {
                return ResourceManager.GetString("MasterMaintenanceRecordNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Select Only One Selection..
        /// </summary>
        internal static string OnlyOneSelection {
            get {
                return ResourceManager.GetString("OnlyOneSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter {0} !.
        /// </summary>
        internal static string PleaseEnter {
            get {
                return ResourceManager.GetString("PleaseEnter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Must be {1} {2}.
        /// </summary>
        internal static string RangeError {
            get {
                return ResourceManager.GetString("RangeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bale Usage Situation Lot {0}, {1} Not Allowed! Lot Already Issues..
        /// </summary>
        internal static string RawMatlBaleUsageActionStoped {
            get {
                return ResourceManager.GetString("RawMatlBaleUsageActionStoped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Raw Material, Item No {0} Not Found..
        /// </summary>
        internal static string RawMatlItemNotFound {
            get {
                return ResourceManager.GetString("RawMatlItemNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raw Material Requisition Lot {0}, {1} Not Allowed! Lot Already Received..
        /// </summary>
        internal static string RawMatlRequisitionActionStoped {
            get {
                return ResourceManager.GetString("RawMatlRequisitionActionStoped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Items Found, At Least 1 Lot Item Must Be Filled..
        /// </summary>
        internal static string RawMatlRequisitionLotItemEmpty {
            get {
                return ResourceManager.GetString("RawMatlRequisitionLotItemEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Lot No {0}  Bale, Requested Bale Must Greater Than 0..
        /// </summary>
        internal static string RawMatlRequisitionLotReqBaleZero {
            get {
                return ResourceManager.GetString("RawMatlRequisitionLotReqBaleZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Lot No {0} Weight, Requested Weight Must Greater Than 0..
        /// </summary>
        internal static string RawMatlRequisitionLotReqWeightZero {
            get {
                return ResourceManager.GetString("RawMatlRequisitionLotReqWeightZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Does Not Exists!.
        /// </summary>
        internal static string RecordNotExists {
            get {
                return ResourceManager.GetString("RecordNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record Not Found!.
        /// </summary>
        internal static string RecordNotFound {
            get {
                return ResourceManager.GetString("RecordNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Successfully!.
        /// </summary>
        internal static string Successfully {
            get {
                return ResourceManager.GetString("Successfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning! System Error!.
        /// </summary>
        internal static string SystemFailed {
            get {
                return ResourceManager.GetString("SystemFailed", resourceCulture);
            }
        }
    }
}