'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.5420
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option or rebuild the Visual Studio project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "9.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class Message
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Resources.Message", Global.System.Reflection.[Assembly].Load("App_GlobalResources"))
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Access Denied!.
        '''</summary>
        Friend Shared ReadOnly Property AccessDenied() As String
            Get
                Return ResourceManager.GetString("AccessDenied", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {0} Already Exists!.
        '''</summary>
        Friend Shared ReadOnly Property AlreadyExists() As String
            Get
                Return ResourceManager.GetString("AlreadyExists", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Please Select At Least One Selection..
        '''</summary>
        Friend Shared ReadOnly Property AtLeastOneSelection() As String
            Get
                Return ResourceManager.GetString("AtLeastOneSelection", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {0} Must be Between {1} and {2}.
        '''</summary>
        Friend Shared ReadOnly Property Between() As String
            Get
                Return ResourceManager.GetString("Between", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The condition is empty..
        '''</summary>
        Friend Shared ReadOnly Property ConditionEmpty() As String
            Get
                Return ResourceManager.GetString("ConditionEmpty", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Are you going to delete the search condition?.
        '''</summary>
        Friend Shared ReadOnly Property ConfirmDeleteConditionMsg() As String
            Get
                Return ResourceManager.GetString("ConfirmDeleteConditionMsg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {0} Must Be {1} or {2}.
        '''</summary>
        Friend Shared ReadOnly Property ContainValue() As String
            Get
                Return ResourceManager.GetString("ContainValue", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Continue without search condition?.
        '''</summary>
        Friend Shared ReadOnly Property ContinueWithoutCondition() As String
            Get
                Return ResourceManager.GetString("ContinueWithoutCondition", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Data No Ready - {0}.
        '''</summary>
        Friend Shared ReadOnly Property DataNoReady() As String
            Get
                Return ResourceManager.GetString("DataNoReady", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Data In {0} Table Not Defined!.
        '''</summary>
        Friend Shared ReadOnly Property DataNotDefine() As String
            Get
                Return ResourceManager.GetString("DataNotDefine", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {0} Must be {1}.
        '''</summary>
        Friend Shared ReadOnly Property DataTypeError() As String
            Get
                Return ResourceManager.GetString("DataTypeError", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Invalid Date Format. e.g. 01-Feb-2001.
        '''</summary>
        Friend Shared ReadOnly Property DateDDMMMYYYYFormat() As String
            Get
                Return ResourceManager.GetString("DateDDMMMYYYYFormat", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {0}, Invalid Date Format. e.g. 28-02-2013!.
        '''</summary>
        Friend Shared ReadOnly Property DateDDMMYYYYFormat() As String
            Get
                Return ResourceManager.GetString("DateDDMMYYYYFormat", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Invalid Account Month Format. (YYYYMM).
        '''</summary>
        Friend Shared ReadOnly Property DateYYYYMMFormat() As String
            Get
                Return ResourceManager.GetString("DateYYYYMMFormat", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Are you sure want to delete this record?.
        '''</summary>
        Friend Shared ReadOnly Property DeleteConfirmation() As String
            Get
                Return ResourceManager.GetString("DeleteConfirmation", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Please Choose Yes to confirm delete.
        '''</summary>
        Friend Shared ReadOnly Property Deletemessage() As String
            Get
                Return ResourceManager.GetString("Deletemessage", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Duplicate {0}!.
        '''</summary>
        Friend Shared ReadOnly Property Duplicate() As String
            Get
                Return ResourceManager.GetString("Duplicate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Warning :.
        '''</summary>
        Friend Shared ReadOnly Property ErrorHeader() As String
            Get
                Return ResourceManager.GetString("ErrorHeader", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {0} Failed!.
        '''</summary>
        Friend Shared ReadOnly Property Failed() As String
            Get
                Return ResourceManager.GetString("Failed", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {0} Cannot be Empty!.
        '''</summary>
        Friend Shared ReadOnly Property FieldEmpty() As String
            Get
                Return ResourceManager.GetString("FieldEmpty", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {0} must in Alphanumeric Format!.
        '''</summary>
        Friend Shared ReadOnly Property FieldFormatAlphanumericError() As String
            Get
                Return ResourceManager.GetString("FieldFormatAlphanumericError", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {0} must in Numeric Format!.
        '''</summary>
        Friend Shared ReadOnly Property FieldFormatNumericError() As String
            Get
                Return ResourceManager.GetString("FieldFormatNumericError", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Finished Goods Transfer Note {0}, {1} Not Allowed! Note Already Closed..
        '''</summary>
        Friend Shared ReadOnly Property FinGoodsTransferActionStoped() As String
            Get
                Return ResourceManager.GetString("FinGoodsTransferActionStoped", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to No Items Found, At Least 1 Item Must Be Filled..
        '''</summary>
        Friend Shared ReadOnly Property FinGoodsTransferItemEmpty() As String
            Get
                Return ResourceManager.GetString("FinGoodsTransferItemEmpty", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Invalid Item No {0} Quantity, Transfer Quantity Must Greater Than 0..
        '''</summary>
        Friend Shared ReadOnly Property FinGoodsTransferItemQtyZero() As String
            Get
                Return ResourceManager.GetString("FinGoodsTransferItemQtyZero", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Finished Goods Transfer, {0} Not Allowed! Month-End Closing Already Run..
        '''</summary>
        Friend Shared ReadOnly Property FinGoodsTransferMonthEndClosed() As String
            Get
                Return ResourceManager.GetString("FinGoodsTransferMonthEndClosed", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Invalid Pallet No {0} Quantity, Pallet Quantity Must Greater Than 0..
        '''</summary>
        Friend Shared ReadOnly Property FinGoodsTransferPalletQtyZero() As String
            Get
                Return ResourceManager.GetString("FinGoodsTransferPalletQtyZero", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Invalid character for advance search.
        '''</summary>
        Friend Shared ReadOnly Property InvalidAdvanceSearch() As String
            Get
                Return ResourceManager.GetString("InvalidAdvanceSearch", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Invalid character for basic search.
        '''</summary>
        Friend Shared ReadOnly Property InvalidBasicSearch() As String
            Get
                Return ResourceManager.GetString("InvalidBasicSearch", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Invalid Receiving Lot and Item, Existing Lot {0} for Specified Item {1} Not Found!.
        '''</summary>
        Friend Shared ReadOnly Property InvalidItemNo_ReceivedLot() As String
            Get
                Return ResourceManager.GetString("InvalidItemNo_ReceivedLot", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Invalid {0}.
        '''</summary>
        Friend Shared ReadOnly Property InvalidPasswordUserName() As String
            Get
                Return ResourceManager.GetString("InvalidPasswordUserName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Invalid Process!.
        '''</summary>
        Friend Shared ReadOnly Property InvalidProcess() As String
            Get
                Return ResourceManager.GetString("InvalidProcess", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Invalid Selection.
        '''</summary>
        Friend Shared ReadOnly Property InvalidSelect() As String
            Get
                Return ResourceManager.GetString("InvalidSelect", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Invalid {0}, Record Not Found In Master Table..
        '''</summary>
        Friend Shared ReadOnly Property MasterMaintenanceRecordNotFound() As String
            Get
                Return ResourceManager.GetString("MasterMaintenanceRecordNotFound", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Please Select Only One Selection..
        '''</summary>
        Friend Shared ReadOnly Property OnlyOneSelection() As String
            Get
                Return ResourceManager.GetString("OnlyOneSelection", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Please Enter {0} !.
        '''</summary>
        Friend Shared ReadOnly Property PleaseEnter() As String
            Get
                Return ResourceManager.GetString("PleaseEnter", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {0} Must be {1} {2}.
        '''</summary>
        Friend Shared ReadOnly Property RangeError() As String
            Get
                Return ResourceManager.GetString("RangeError", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Bale Usage Situation Lot {0}, {1} Not Allowed! Lot Already Issues..
        '''</summary>
        Friend Shared ReadOnly Property RawMatlBaleUsageActionStoped() As String
            Get
                Return ResourceManager.GetString("RawMatlBaleUsageActionStoped", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Invalid Raw Material, Item No {0} Not Found..
        '''</summary>
        Friend Shared ReadOnly Property RawMatlItemNotFound() As String
            Get
                Return ResourceManager.GetString("RawMatlItemNotFound", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Raw Material Requisition Lot {0}, {1} Not Allowed! Lot Already Received..
        '''</summary>
        Friend Shared ReadOnly Property RawMatlRequisitionActionStoped() As String
            Get
                Return ResourceManager.GetString("RawMatlRequisitionActionStoped", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to No Items Found, At Least 1 Lot Item Must Be Filled..
        '''</summary>
        Friend Shared ReadOnly Property RawMatlRequisitionLotItemEmpty() As String
            Get
                Return ResourceManager.GetString("RawMatlRequisitionLotItemEmpty", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Invalid Lot No {0}  Bale, Requested Bale Must Greater Than 0..
        '''</summary>
        Friend Shared ReadOnly Property RawMatlRequisitionLotReqBaleZero() As String
            Get
                Return ResourceManager.GetString("RawMatlRequisitionLotReqBaleZero", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Invalid Lot No {0} Weight, Requested Weight Must Greater Than 0..
        '''</summary>
        Friend Shared ReadOnly Property RawMatlRequisitionLotReqWeightZero() As String
            Get
                Return ResourceManager.GetString("RawMatlRequisitionLotReqWeightZero", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {0} Does Not Exists!.
        '''</summary>
        Friend Shared ReadOnly Property RecordNotExists() As String
            Get
                Return ResourceManager.GetString("RecordNotExists", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Record Not Found!.
        '''</summary>
        Friend Shared ReadOnly Property RecordNotFound() As String
            Get
                Return ResourceManager.GetString("RecordNotFound", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {0} Successfully!.
        '''</summary>
        Friend Shared ReadOnly Property Successfully() As String
            Get
                Return ResourceManager.GetString("Successfully", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Warning! System Error!.
        '''</summary>
        Friend Shared ReadOnly Property SystemFailed() As String
            Get
                Return ResourceManager.GetString("SystemFailed", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
