//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SearchSource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SearchSource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.SearchSource", typeof(SearchSource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;Text&quot;:&quot;Code&quot;,&quot;Value&quot;:&quot;CODE&quot;},{&quot;T....
        /// </summary>
        internal static string MM_COMM_FIELD {
            get {
                return ResourceManager.GetString("MM_COMM_FIELD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;Text&quot;:&quot;Company Code&quot;, &quot;Value&quot;:&quot;COMPANYCODE....
        /// </summary>
        internal static string MM_COMPANY {
            get {
                return ResourceManager.GetString("MM_COMPANY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [ {&quot;Text&quot;:&quot;Section&quot;, &quot;Value&quot;:&quot;SEC_DESC&quot;}....
        /// </summary>
        internal static string MM_Email_Group {
            get {
                return ResourceManager.GetString("MM_Email_Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;Text&quot;:&quot;Email Group Description&quot;, &quot;Value&quot;:&quot;....
        /// </summary>
        internal static string MM_Email_List {
            get {
                return ResourceManager.GetString("MM_Email_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;Text&quot;:&quot;Carrier Code&quot;, &quot;Value&quot;:&quot;EQUIPMENT_C....
        /// </summary>
        internal static string MM_Equipment {
            get {
                return ResourceManager.GetString("MM_Equipment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [ {&quot;Text&quot;:&quot;Carrier Name&quot;, &quot;Value&quot;:&quot;EQUIPMENT_....
        /// </summary>
        internal static string MM_Equipment_Reg {
            get {
                return ResourceManager.GetString("MM_Equipment_Reg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;Text&quot;:&quot;Setup&quot;,&quot;Value&quot;:&quot;setup&quot;},
{&quo....
        /// </summary>
        internal static string MM_Mac_Cond {
            get {
                return ResourceManager.GetString("MM_Mac_Cond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;Text&quot;:&quot;PC1&quot;, &quot;Value&quot;:&quot;PC1&quot;},{&quot;Te....
        /// </summary>
        internal static string MM_PC1 {
            get {
                return ResourceManager.GetString("MM_PC1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;Text&quot;:&quot;PC2&quot;, &quot;Value&quot;:&quot;PC2&quot;},{&quot;Te....
        /// </summary>
        internal static string MM_PC2 {
            get {
                return ResourceManager.GetString("MM_PC2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;Text&quot;:&quot;PC2&quot;, &quot;Value&quot;:&quot;PC2M&quot;},{&quot;T....
        /// </summary>
        internal static string MM_PC2_MOTHER {
            get {
                return ResourceManager.GetString("MM_PC2_MOTHER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;Text&quot;:&quot;Product Line&quot;,&quot;Value&quot;:&quot;PRODLINE_NO&....
        /// </summary>
        internal static string MM_PRODLINE {
            get {
                return ResourceManager.GetString("MM_PRODLINE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;Text&quot;:&quot;RFID Location Area&quot;, &quot;Value&quot;:&quot;RFID_....
        /// </summary>
        internal static string MM_RFID_LOC_AREA {
            get {
                return ResourceManager.GetString("MM_RFID_LOC_AREA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;Text&quot;:&quot;Plant&quot;, &quot;Value&quot;:&quot;PLANT&quot;},{&quo....
        /// </summary>
        internal static string MM_RFID_LOC_READER_REG {
            get {
                return ResourceManager.GetString("MM_RFID_LOC_READER_REG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;Text&quot;:&quot;RFID Type&quot;, &quot;Value&quot;:&quot;RFID_TYPE&quot....
        /// </summary>
        internal static string MM_RFID_Type {
            get {
                return ResourceManager.GetString("MM_RFID_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;Text&quot;:&quot;Chop  No&quot;,&quot;Value&quot;:&quot;CHOP_NO&quot;}].
        /// </summary>
        internal static string MM_ST_CONTROL {
            get {
                return ResourceManager.GetString("MM_ST_CONTROL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;Text&quot;:&quot;UserID&quot;, &quot;Value&quot;:&quot;USERID&quot;},{&q....
        /// </summary>
        internal static string MM_USER {
            get {
                return ResourceManager.GetString("MM_USER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;Text&quot;:&quot;Ref No&quot;, &quot;Value&quot;:&quot;REFNO&quot;},{&qu....
        /// </summary>
        internal static string PC2_LOTNO {
            get {
                return ResourceManager.GetString("PC2_LOTNO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;Text&quot;:&quot;Chop No&quot;,&quot;Value&quot;:&quot;CHOP_NO&quot;}].
        /// </summary>
        internal static string PP_ChopNo {
            get {
                return ResourceManager.GetString("PP_ChopNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;Text&quot;:&quot;Production Order No&quot;,&quot;Value&quot;:&quot;PROD_....
        /// </summary>
        internal static string PP_Order_Detail {
            get {
                return ResourceManager.GetString("PP_Order_Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;Text&quot;:&quot;PC 2 Mother&quot;,&quot;Value&quot;:&quot;PC2&quot;}].
        /// </summary>
        internal static string PP_PC2 {
            get {
                return ResourceManager.GetString("PP_PC2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;Text&quot;:&quot;Product Code 2&quot;,&quot;Value&quot;:&quot;PC2&quot;}....
        /// </summary>
        internal static string PP_PC2SUB {
            get {
                return ResourceManager.GetString("PP_PC2SUB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;Text&quot;:&quot;PC 2 Customer&quot;,&quot;Value&quot;:&quot;PC2&quot;}].
        /// </summary>
        internal static string PP_PC2_Cust {
            get {
                return ResourceManager.GetString("PP_PC2_Cust", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;Text&quot;:&quot;PO  No&quot;,&quot;Value&quot;:&quot;PROD_ORDER_NO&quot....
        /// </summary>
        internal static string PP_PO {
            get {
                return ResourceManager.GetString("PP_PO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;Text&quot;:&quot;Printer Name&quot;,&quot;Value&quot;:&quot;Printer_Name....
        /// </summary>
        internal static string PRINT_ALIGN_INIT {
            get {
                return ResourceManager.GetString("PRINT_ALIGN_INIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;Text&quot;:&quot;Reference No&quot;, &quot;Value&quot;:&quot;REFNO&quot;....
        /// </summary>
        internal static string PV_SUBSLIT_REQUEST_LIST {
            get {
                return ResourceManager.GetString("PV_SUBSLIT_REQUEST_LIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;Text&quot;:&quot;Ref No&quot;, &quot;Value&quot;:&quot;REFNO&quot;},{&qu....
        /// </summary>
        internal static string VIEW_LOT_SLITTING_SERIES {
            get {
                return ResourceManager.GetString("VIEW_LOT_SLITTING_SERIES", resourceCulture);
            }
        }
    }
}