'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.5420
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option or rebuild the Visual Studio project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "9.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class SearchSource
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Resources.SearchSource", Global.System.Reflection.[Assembly].Load("App_GlobalResources"))
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to [{&quot;Text&quot;:&quot;Code&quot;,&quot;Value&quot;:&quot;CODE&quot;},{&quot;Text&quot;:&quot;Description&quot;,&quot;Value&quot;:&quot;CODE_DESC&quot;}].
        '''</summary>
        Friend Shared ReadOnly Property MM_COMM_FIELD() As String
            Get
                Return ResourceManager.GetString("MM_COMM_FIELD", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to [ {&quot;Text&quot;:&quot;Section&quot;, &quot;Value&quot;:&quot;SEC_DESC&quot;},
        '''{&quot;Text&quot;:&quot;Email Group Name&quot;, &quot;Value&quot;:&quot;EMAIL_GROUP_NAME&quot;},
        '''{&quot;Text&quot;:&quot;Email Group Description&quot;, &quot;Value&quot;:&quot;EMAIL_GROUP_DESC&quot;}].
        '''</summary>
        Friend Shared ReadOnly Property MM_Email_Group() As String
            Get
                Return ResourceManager.GetString("MM_Email_Group", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to [{&quot;Text&quot;:&quot;Email Group Description&quot;, &quot;Value&quot;:&quot;EMAIL_GROUP_DESC&quot;}
        '''].
        '''</summary>
        Friend Shared ReadOnly Property MM_Email_List() As String
            Get
                Return ResourceManager.GetString("MM_Email_List", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to [{&quot;Text&quot;:&quot;Carrier Code&quot;, &quot;Value&quot;:&quot;EQUIPMENT_CODE&quot;}, {&quot;Text&quot;:&quot;Carrier Name&quot;, &quot;Value&quot;:&quot;EQUIPMENT_NAME&quot;}].
        '''</summary>
        Friend Shared ReadOnly Property MM_Equipment() As String
            Get
                Return ResourceManager.GetString("MM_Equipment", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to [ {&quot;Text&quot;:&quot;Carrier Name&quot;, &quot;Value&quot;:&quot;EQUIPMENT_NAME&quot;},{&quot;Text&quot;:&quot;RFID Type&quot;, &quot;Value&quot;:&quot;RFID_TYPE&quot;}, {&quot;Text&quot;:&quot;Batch ID&quot;, &quot;Value&quot;:&quot;BATCH_ID&quot;}, {&quot;Text&quot;:&quot;RFID ID&quot;, &quot;Value&quot;:&quot;ID_RFID&quot;}, {&quot;Text&quot;:&quot;RFID ID 2&quot;, &quot;Value&quot;:&quot;ID_RFID_2&quot;}].
        '''</summary>
        Friend Shared ReadOnly Property MM_Equipment_Reg() As String
            Get
                Return ResourceManager.GetString("MM_Equipment_Reg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to [{&quot;Text&quot;:&quot;Setup&quot;,&quot;Value&quot;:&quot;setup&quot;},
        '''{&quot;Text&quot;:&quot;Section&quot;,&quot;Value&quot;:&quot;Section&quot;},
        '''{&quot;Text&quot;:&quot;Process&quot;,&quot;Value&quot;:&quot;Process&quot;}].
        '''</summary>
        Friend Shared ReadOnly Property MM_Mac_Cond() As String
            Get
                Return ResourceManager.GetString("MM_Mac_Cond", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to [{&quot;Text&quot;:&quot;RFID Location Area&quot;, &quot;Value&quot;:&quot;RFID_LOC_AREA&quot;}].
        '''</summary>
        Friend Shared ReadOnly Property MM_RFID_LOC_AREA() As String
            Get
                Return ResourceManager.GetString("MM_RFID_LOC_AREA", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to [{&quot;Text&quot;:&quot;Plant&quot;, &quot;Value&quot;:&quot;PLANT&quot;},{&quot;Text&quot;:&quot;Section&quot;, &quot;Value&quot;:&quot;SEC_DESC&quot;},{&quot;Text&quot;:&quot;RFID CEL Reader Name&quot;, &quot;Value&quot;:&quot;RFID_CEL_READER_NAME&quot;},{&quot;Text&quot;:&quot;Location Name&quot;, &quot;Value&quot;:&quot;LOCATION_NAME&quot;},{&quot;Text&quot;:&quot;RFID Location Area&quot;, &quot;Value&quot;:&quot;RFID_LOC_AREA&quot;},{&quot;Text&quot;:&quot;IP Address&quot;, &quot;Value&quot;:&quot;IP_ADDRESS&quot;},{&quot;Text&quot;:&quot;Configuration Path&quot;, &quot;Value&quot;:&quot;APPL_PATH_URL&quot;}].
        '''</summary>
        Friend Shared ReadOnly Property MM_RFID_LOC_READER_REG() As String
            Get
                Return ResourceManager.GetString("MM_RFID_LOC_READER_REG", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to [{&quot;Text&quot;:&quot;RFID Type&quot;, &quot;Value&quot;:&quot;RFID_TYPE&quot;}].
        '''</summary>
        Friend Shared ReadOnly Property MM_RFID_Type() As String
            Get
                Return ResourceManager.GetString("MM_RFID_Type", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to [{&quot;Text&quot;:&quot;Chop  No&quot;,&quot;Value&quot;:&quot;CHOP_NO&quot;}].
        '''</summary>
        Friend Shared ReadOnly Property MM_ST_CONTROL() As String
            Get
                Return ResourceManager.GetString("MM_ST_CONTROL", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to [{&quot;Text&quot;:&quot;UserID&quot;, &quot;Value&quot;:&quot;USERID&quot;},{&quot;Text&quot;:&quot;Name&quot;, &quot;Value&quot;:&quot;NAME&quot;},{&quot;Text&quot;:&quot;Department&quot;, &quot;Value&quot;:&quot;DEPARTMENT&quot;},{&quot;Text&quot;:&quot;Email Address&quot;, &quot;Value&quot;:&quot;EMAIL&quot;},{&quot;Text&quot;:&quot;Level&quot;, &quot;Value&quot;:&quot;ULEVEL&quot;},{&quot;Text&quot;:&quot;Created Date&quot;, &quot;Value&quot;:&quot;CREATED_DATE&quot;},{&quot;Text&quot;:&quot;Updated Date&quot;, &quot;Value&quot;:&quot;UPDATED_DATE&quot;], {&quot;Text&quot;:&quot;Record Type&quot;, &quot;Value&quot;:&quot;REC_TYPE&quot;].
        '''</summary>
        Friend Shared ReadOnly Property MM_USER() As String
            Get
                Return ResourceManager.GetString("MM_USER", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to [{&quot;Text&quot;:&quot;UserID&quot;, &quot;Value&quot;:&quot;USERID&quot;},{&quot;Text&quot;:&quot;Name&quot;, &quot;Value&quot;:&quot;NAME&quot;},{&quot;Text&quot;:&quot;Department&quot;, &quot;Value&quot;:&quot;DEPARTMENT&quot;},{&quot;Text&quot;:&quot;Email Address&quot;, &quot;Value&quot;:&quot;EMAIL&quot;},{&quot;Text&quot;:&quot;Level&quot;, &quot;Value&quot;:&quot;ULEVEL&quot;},{&quot;Text&quot;:&quot;Created Date&quot;, &quot;Value&quot;:&quot;CREATED_DATE&quot;},{&quot;Text&quot;:&quot;Updated Date&quot;, &quot;Value&quot;:&quot;UPDATED_DATE&quot;], {&quot;Text&quot;:&quot;Record Type&quot;, &quot;Value&quot;:&quot;REC_TYPE&quot;].
        '''</summary>
        Friend Shared ReadOnly Property MM_PC1() As String
            Get
                Return ResourceManager.GetString("MM_PC1", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to [{&quot;Text&quot;:&quot;UserID&quot;, &quot;Value&quot;:&quot;USERID&quot;},{&quot;Text&quot;:&quot;Name&quot;, &quot;Value&quot;:&quot;NAME&quot;},{&quot;Text&quot;:&quot;Department&quot;, &quot;Value&quot;:&quot;DEPARTMENT&quot;},{&quot;Text&quot;:&quot;Email Address&quot;, &quot;Value&quot;:&quot;EMAIL&quot;},{&quot;Text&quot;:&quot;Level&quot;, &quot;Value&quot;:&quot;ULEVEL&quot;},{&quot;Text&quot;:&quot;Created Date&quot;, &quot;Value&quot;:&quot;CREATED_DATE&quot;},{&quot;Text&quot;:&quot;Updated Date&quot;, &quot;Value&quot;:&quot;UPDATED_DATE&quot;], {&quot;Text&quot;:&quot;Record Type&quot;, &quot;Value&quot;:&quot;REC_TYPE&quot;].
        '''</summary>
        Friend Shared ReadOnly Property MM_PC2_MOTHER() As String
            Get
                Return ResourceManager.GetString("MM_PC2_MOTHER", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to [{&quot;Text&quot;:&quot;UserID&quot;, &quot;Value&quot;:&quot;USERID&quot;},{&quot;Text&quot;:&quot;Name&quot;, &quot;Value&quot;:&quot;NAME&quot;},{&quot;Text&quot;:&quot;Department&quot;, &quot;Value&quot;:&quot;DEPARTMENT&quot;},{&quot;Text&quot;:&quot;Email Address&quot;, &quot;Value&quot;:&quot;EMAIL&quot;},{&quot;Text&quot;:&quot;Level&quot;, &quot;Value&quot;:&quot;ULEVEL&quot;},{&quot;Text&quot;:&quot;Created Date&quot;, &quot;Value&quot;:&quot;CREATED_DATE&quot;},{&quot;Text&quot;:&quot;Updated Date&quot;, &quot;Value&quot;:&quot;UPDATED_DATE&quot;], {&quot;Text&quot;:&quot;Record Type&quot;, &quot;Value&quot;:&quot;REC_TYPE&quot;].
        '''</summary>
        Friend Shared ReadOnly Property PRINT_ALIGN_INIT() As String
            Get
                Return ResourceManager.GetString("PRINT_ALIGN_INIT", resourceCulture)
            End Get
        End Property

        Friend Shared ReadOnly Property MM_PC2() As String
            Get
                Return ResourceManager.GetString("MM_PC2", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to [{&quot;Text&quot;:&quot;UserID&quot;, &quot;Value&quot;:&quot;USERID&quot;},{&quot;Text&quot;:&quot;Name&quot;, &quot;Value&quot;:&quot;NAME&quot;},{&quot;Text&quot;:&quot;Department&quot;, &quot;Value&quot;:&quot;DEPARTMENT&quot;},{&quot;Text&quot;:&quot;Email Address&quot;, &quot;Value&quot;:&quot;EMAIL&quot;},{&quot;Text&quot;:&quot;Level&quot;, &quot;Value&quot;:&quot;ULEVEL&quot;},{&quot;Text&quot;:&quot;Created Date&quot;, &quot;Value&quot;:&quot;CREATED_DATE&quot;},{&quot;Text&quot;:&quot;Updated Date&quot;, &quot;Value&quot;:&quot;UPDATED_DATE&quot;], {&quot;Text&quot;:&quot;Record Type&quot;, &quot;Value&quot;:&quot;REC_TYPE&quot;].
        '''</summary>
        Friend Shared ReadOnly Property MM_COMPANY() As String
            Get
                Return ResourceManager.GetString("MM_COMPANY", resourceCulture)
            End Get
        End Property

        Friend Shared ReadOnly Property MM_PRODLINE() As String
            Get
                Return ResourceManager.GetString("MM_PRODLINE", resourceCulture)
            End Get
        End Property

        Friend Shared ReadOnly Property PC2_LOTNO() As String
            Get
                Return ResourceManager.GetString("PC2_LOTNO", resourceCulture)
            End Get
        End Property


        '''<summary>
        '''  Looks up a localized string similar to [{&quot;Text&quot;:&quot;UserID&quot;, &quot;Value&quot;:&quot;USERID&quot;},{&quot;Text&quot;:&quot;Name&quot;, &quot;Value&quot;:&quot;NAME&quot;},{&quot;Text&quot;:&quot;Department&quot;, &quot;Value&quot;:&quot;DEPARTMENT&quot;},{&quot;Text&quot;:&quot;Email Address&quot;, &quot;Value&quot;:&quot;EMAIL&quot;},{&quot;Text&quot;:&quot;Level&quot;, &quot;Value&quot;:&quot;ULEVEL&quot;},{&quot;Text&quot;:&quot;Created Date&quot;, &quot;Value&quot;:&quot;CREATED_DATE&quot;},{&quot;Text&quot;:&quot;Updated Date&quot;, &quot;Value&quot;:&quot;UPDATED_DATE&quot;], {&quot;Text&quot;:&quot;Record Type&quot;, &quot;Value&quot;:&quot;REC_TYPE&quot;].
        '''</summary>
        Friend Shared ReadOnly Property VIEW_LOT_SLITTING_SERIES() As String
            Get
                Return ResourceManager.GetString("VIEW_LOT_SLITTING_SERIES", resourceCulture)
            End Get
        End Property

        Friend Shared ReadOnly Property PV_SUBSLIT_REQUEST_LIST() As String
            Get
                Return ResourceManager.GetString("PV_SUBSLIT_REQUEST_LIST", resourceCulture)
            End Get
        End Property


        '''<summary>
        '''  Looks up a localized string similar to [{&quot;Text&quot;:&quot;Chop No&quot;,&quot;Value&quot;:&quot;CHOP_NO&quot;}].
        '''</summary>
        Friend Shared ReadOnly Property PP_ChopNo() As String
            Get
                Return ResourceManager.GetString("PP_ChopNo", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to [{&quot;Text&quot;:&quot;Production Order No&quot;,&quot;Value&quot;:&quot;PROD_ORDER_NO&quot;},
        '''{&quot;Text&quot;:&quot;PO Serial No&quot;,&quot;Value&quot;:&quot;PO_SERIAL_NO&quot;},
        '''{&quot;Text&quot;:&quot;Chop No&quot;,&quot;Value&quot;:&quot;CHOP_NO&quot;},
        '''{&quot;Text&quot;:&quot;Finish Code&quot;,&quot;Value&quot;:&quot;FINCODE&quot;}].
        '''</summary>
        Friend Shared ReadOnly Property PP_Order_Detail() As String
            Get
                Return ResourceManager.GetString("PP_Order_Detail", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to [{&quot;Text&quot;:&quot;PO  No&quot;,&quot;Value&quot;:&quot;PROD_ORDER_NO&quot;}].
        '''</summary>
        Friend Shared ReadOnly Property PP_PO() As String
            Get
                Return ResourceManager.GetString("PP_PO", resourceCulture)
            End Get
        End Property

        Friend Shared ReadOnly Property PP_PC2() As String
            Get
                Return ResourceManager.GetString("PP_PC2", resourceCulture)
            End Get
        End Property

        Friend Shared ReadOnly Property PP_PC2_Cust() As String
            Get
                Return ResourceManager.GetString("PP_PC2_Cust", resourceCulture)
            End Get
        End Property
    End Class

End Namespace
