//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

public partial class UserControl_GridFooter : System.Web.UI.UserControl
{
    protected global::System.Web.UI.WebControls.Label lblTotalRecord;
    protected global::System.Web.UI.WebControls.ImageButton btnFirst;
    protected global::System.Web.UI.WebControls.ImageButton btnPrevious;
    protected global::System.Web.UI.WebControls.DropDownList ddlPage;
    protected global::System.Web.UI.WebControls.ImageButton btnNext;
    protected global::System.Web.UI.WebControls.ImageButton btnLast;
}
