//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

public partial class UserControl_GridHeader : System.Web.UI.UserControl
{
    protected global::System.Web.UI.WebControls.DropDownList ddlAction;
    protected global::System.Web.UI.HtmlControls.HtmlAnchor hypAdd;
}
