//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

public partial class App_Module_SearchForPPFabric
{
    protected global::System.Web.UI.WebControls.Label lblSearch;
    protected global::System.Web.UI.WebControls.Panel pnlBasic;
    protected global::System.Web.UI.WebControls.DropDownList ddlSearch;
    protected global::System.Web.UI.WebControls.TextBox txtSearch;
    protected global::System.Web.UI.WebControls.Button btnSubmit;
    protected global::System.Web.UI.WebControls.LinkButton lbAdvSearch;
    protected global::System.Web.UI.WebControls.Panel pnlAdvance;
    protected global::System.Web.UI.WebControls.DropDownList ddlSearchUsing;
    protected global::System.Web.UI.WebControls.DropDownList ddlOperator1;
    protected global::System.Web.UI.WebControls.TextBox txtSearchUsing;
    protected global::System.Web.UI.WebControls.DropDownList ddlSearch2;
    protected global::System.Web.UI.WebControls.Button btnPlus;
    protected global::System.Web.UI.WebControls.ListBox searchCriteria;
    protected global::System.Web.UI.WebControls.Button btnMinus;
    protected global::System.Web.UI.WebControls.Button btnSubmit2;
    protected global::System.Web.UI.WebControls.Button btnReset;
    protected global::System.Web.UI.WebControls.LinkButton lbBasicSearch;
    protected global::System.Web.UI.WebControls.CheckBox chkDeleted;
}
