//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

public partial class App_Module_Title : System.Web.UI.UserControl
{
    protected global::System.Web.UI.WebControls.Label lblFormTitle;
}
