//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

public partial class Captcha
{
    protected global::System.Web.UI.HtmlControls.HtmlForm form1;
}
