//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

public partial class Log : Control.LogBase
{
    protected global::System.Web.UI.HtmlControls.HtmlHead Head1;
    protected global::System.Web.UI.HtmlControls.HtmlForm form1;
    protected global::App_Module_Title UCTitle;
    protected global::System.Web.UI.HtmlControls.HtmlGenericControl divDesc;
    protected global::System.Web.UI.WebControls.GridView grdResult;
    protected global::UserControl_GridFooter UCFooter;
    protected global::System.Web.UI.WebControls.Button btnclose;
}
