//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

public partial class Menu
{
    protected global::System.Web.UI.HtmlControls.HtmlHead Head1;
    protected global::System.Web.UI.WebControls.Literal liItems;
    protected global::System.Web.UI.HtmlControls.HtmlGenericControl trhome;
    protected global::System.Web.UI.HtmlControls.HtmlGenericControl resetpwd;
}
