//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

public partial class PopUp_PP_PC2SUB : Control.Base
{
    protected global::App_Module_Title UCTitle;
    protected global::System.Web.UI.WebControls.Label lblTittle;
    protected global::Search UCSearch;
    protected global::System.Web.UI.WebControls.GridView grdResult;
    protected global::UserControl_GridFooter UCFooter;
}
