//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

public partial class Transactions_Housekeeping
{
    protected global::System.Web.UI.WebControls.DropDownList ddlDataRet;
    protected global::System.Web.UI.WebControls.RequiredFieldValidator rfddlDataRet;
    protected global::System.Web.UI.WebControls.Label lbCurrDate;
    protected global::System.Web.UI.WebControls.Button btnupdate;
    protected global::System.Web.UI.WebControls.Button btnreset;
}
