//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

public partial class Transactions_SSR_SEARCH_Dtl
{
    protected global::System.Web.UI.WebControls.Label lbltittle;
    protected global::System.Web.UI.WebControls.Label Label1;
    protected global::System.Web.UI.WebControls.Label Label2;
    protected global::System.Web.UI.WebControls.Label lblCompCode;
    protected global::System.Web.UI.WebControls.Label Label3;
    protected global::System.Web.UI.WebControls.Label Label4;
    protected global::System.Web.UI.WebControls.Label lblRefNo;
    protected global::System.Web.UI.WebControls.Label Label5;
    protected global::System.Web.UI.WebControls.Label Label6;
    protected global::System.Web.UI.WebControls.Label lblDept;
    protected global::System.Web.UI.WebControls.Label Label7;
    protected global::System.Web.UI.WebControls.Label Label8;
    protected global::System.Web.UI.WebControls.Label lblDate;
    protected global::System.Web.UI.WebControls.Label Label9;
    protected global::System.Web.UI.WebControls.Label Label10;
    protected global::System.Web.UI.WebControls.Label lblBy;
    protected global::System.Web.UI.WebControls.Label Label11;
    protected global::System.Web.UI.WebControls.Label Label12;
    protected global::System.Web.UI.WebControls.Label lblRev;
    protected global::System.Web.UI.WebControls.Label Label13;
    protected global::System.Web.UI.WebControls.Label Label14;
    protected global::System.Web.UI.WebControls.DropDownList ddlReqStat;
    protected global::System.Web.UI.WebControls.Label lblrequest;
    protected global::System.Web.UI.WebControls.Label Label15;
    protected global::System.Web.UI.WebControls.Label Label16;
    protected global::System.Web.UI.WebControls.DropDownList ddlVenStat;
    protected global::System.Web.UI.WebControls.Label lblvendor;
    protected global::System.Web.UI.WebControls.Panel pnlList;
    protected global::System.Web.UI.WebControls.GridView grdList;
    protected global::System.Web.UI.HtmlControls.HtmlTable SSRTotal;
    protected global::System.Web.UI.WebControls.Label lblMQty;
    protected global::System.Web.UI.WebControls.Label lblMTotalWeight;
    protected global::System.Web.UI.WebControls.Label lblCQty;
    protected global::System.Web.UI.WebControls.Label lblCTotalWeight;
    protected global::System.Web.UI.WebControls.Label lblSubSlitWaste;
    protected global::System.Web.UI.WebControls.Button UpdStat_Button;
    protected global::System.Web.UI.WebControls.Button NewRev_Button;
    protected global::System.Web.UI.WebControls.Button Export_Button;
    protected global::System.Web.UI.WebControls.Button Cancel_Button;
    protected global::System.Web.UI.WebControls.Panel pninfo;
    protected global::System.Web.UI.WebControls.Label lblcreatedby;
    protected global::System.Web.UI.WebControls.Label lblcreateddate;
    protected global::System.Web.UI.WebControls.Label lblupdatedby;
    protected global::System.Web.UI.WebControls.Label lblupdateddate;
    protected global::System.Web.UI.WebControls.Panel pnconfirmation;
    protected global::System.Web.UI.WebControls.RadioButton rbyes;
    protected global::System.Web.UI.WebControls.RadioButton rbno;
    protected global::System.Web.UI.WebControls.Button btnSubmit;
    protected global::System.Web.UI.WebControls.Button btnCancel;
}