//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

public partial class Transactions_SUBSLITREQSEARCH : Control.Base
{
    protected global::App_Module_Title UCTitle;
    protected global::Search UCSearch;
    protected global::UserControl_GridHeader UCHeader;
    protected global::System.Web.UI.WebControls.LinkButton Add_Button;
    protected global::System.Web.UI.WebControls.GridView grdResult;
    protected global::UserControl_GridFooter UCFooter;
}
