//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

public partial class Transactions_SubSlitRequest
{
    protected global::System.Web.UI.HtmlControls.HtmlInputHidden inpHide;
    protected global::System.Web.UI.WebControls.Button Button1;
    protected global::System.Web.UI.WebControls.Button Button2;
    protected global::System.Web.UI.WebControls.Button Button3;
    protected global::System.Web.UI.WebControls.DropDownList ddlCompCode;
    protected global::System.Web.UI.WebControls.TextBox txtRefNo;
    protected global::System.Web.UI.WebControls.TextBox txtSubReqId;
    protected global::System.Web.UI.WebControls.Label lblDept;
    protected global::System.Web.UI.WebControls.TextBox txtDate;
    protected global::System.Web.UI.WebControls.Label lblBy;
    protected global::System.Web.UI.WebControls.Label lblRev;
    protected global::System.Web.UI.WebControls.Label lblReqStat;
    protected global::System.Web.UI.WebControls.Label lblVenStat;
    protected global::System.Web.UI.WebControls.TextBox txtSeqMother;
    protected global::System.Web.UI.WebControls.TextBox ddlProdLine;
    protected global::System.Web.UI.WebControls.TextBox ddlPC1;
    protected global::System.Web.UI.WebControls.TextBox ddlPC2;
    protected global::System.Web.UI.HtmlControls.HtmlInputButton btnPC2Mother;
    protected global::System.Web.UI.WebControls.Button btnpc2;
    protected global::System.Web.UI.WebControls.TextBox txtQty;
    protected global::System.Web.UI.WebControls.Label lblUnitWeight;
    protected global::System.Web.UI.WebControls.Label lblTotWeight;
    protected global::System.Web.UI.WebControls.Label lblSubSlit;
    protected global::System.Web.UI.WebControls.TextBox txtETD;
    protected global::System.Web.UI.WebControls.TextBox txtETA;
    protected global::System.Web.UI.WebControls.LinkButton btnNext;
    protected global::System.Web.UI.WebControls.LinkButton btnReset;
    protected global::System.Web.UI.WebControls.Panel pnlChild;
    protected global::System.Web.UI.WebControls.Button btnpc2child;
    protected global::System.Web.UI.WebControls.GridView grdChild;
    protected global::System.Web.UI.WebControls.LinkButton btnAddRow;
    protected global::System.Web.UI.WebControls.LinkButton btnSave;
    protected global::System.Web.UI.WebControls.Panel pnlList;
    protected global::System.Web.UI.WebControls.GridView grdList;
    protected global::System.Web.UI.WebControls.LinkButton btnEdit;
    protected global::System.Web.UI.WebControls.LinkButton btnDelete;
    protected global::System.Web.UI.HtmlControls.HtmlTable SSRTotal;
    protected global::System.Web.UI.WebControls.Label lblMQty;
    protected global::System.Web.UI.WebControls.Label lblMTotalWeight;
    protected global::System.Web.UI.WebControls.Label lblCQty;
    protected global::System.Web.UI.WebControls.Label lblCTotalWeight;
    protected global::System.Web.UI.WebControls.Label lblSubSlitWaste;
    protected global::System.Web.UI.WebControls.Button Submit_Button;
    protected global::System.Web.UI.WebControls.Button Cancel_Button;
}