//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

public partial class Transactions_test
{
    protected global::System.Web.UI.HtmlControls.HtmlForm form1;
    protected global::System.Web.UI.WebControls.Label Label23;
    protected global::System.Web.UI.WebControls.TextBox txtpassword;
    protected global::System.Web.UI.WebControls.Button Button1;
    protected global::System.Web.UI.WebControls.Label Label24;
    protected global::System.Web.UI.WebControls.Button Button2;
    protected global::System.Web.UI.WebControls.Label Label25;
    protected global::System.Web.UI.WebControls.Label Label1;
    protected global::System.Web.UI.WebControls.TextBox txtcipher;
    protected global::System.Web.UI.WebControls.Button Button3;
    protected global::System.Web.UI.WebControls.Label Label2;
}
